/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenegociacaoDemoRouteImport } from './routes/renegociacao-demo'
import { Route as ConsultarCpfIndexRouteImport } from './routes/consultar-cpf.index'
import { Route as ConsultarCpfResultadoRouteImport } from './routes/consultar-cpf.resultado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenegociacaoDemoRoute = RenegociacaoDemoRouteImport.update({
  id: '/renegociacao-demo',
  path: '/renegociacao-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarCpfIndexRoute = ConsultarCpfIndexRouteImport.update({
  id: '/consultar-cpf/',
  path: '/consultar-cpf/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarCpfResultadoRoute = ConsultarCpfResultadoRouteImport.update({
  id: '/consultar-cpf/resultado',
  path: '/consultar-cpf/resultado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/renegociacao-demo': typeof RenegociacaoDemoRoute
  '/consultar-cpf/resultado': typeof ConsultarCpfResultadoRoute
  '/consultar-cpf/': typeof ConsultarCpfIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/renegociacao-demo': typeof RenegociacaoDemoRoute
  '/consultar-cpf/resultado': typeof ConsultarCpfResultadoRoute
  '/consultar-cpf': typeof ConsultarCpfIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/renegociacao-demo': typeof RenegociacaoDemoRoute
  '/consultar-cpf/resultado': typeof ConsultarCpfResultadoRoute
  '/consultar-cpf/': typeof ConsultarCpfIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/renegociacao-demo' | '/consultar-cpf/resultado' | '/consultar-cpf/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/renegociacao-demo' | '/consultar-cpf/resultado' | '/consultar-cpf'
  id:
    | '__root__'
    | '/'
    | '/renegociacao-demo'
    | '/consultar-cpf/resultado'
    | '/consultar-cpf/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RenegociacaoDemoRoute: typeof RenegociacaoDemoRoute
  ConsultarCpfResultadoRoute: typeof ConsultarCpfResultadoRoute
  ConsultarCpfIndexRoute: typeof ConsultarCpfIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renegociacao-demo': {
      id: '/renegociacao-demo'
      path: '/renegociacao-demo'
      fullPath: '/renegociacao-demo'
      preLoaderRoute: typeof RenegociacaoDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar-cpf/': {
      id: '/consultar-cpf/'
      path: '/consultar-cpf'
      fullPath: '/consultar-cpf/'
      preLoaderRoute: typeof ConsultarCpfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar-cpf/resultado': {
      id: '/consultar-cpf/resultado'
      path: '/consultar-cpf/resultado'
      fullPath: '/consultar-cpf/resultado'
      preLoaderRoute: typeof ConsultarCpfResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RenegociacaoDemoRoute: RenegociacaoDemoRoute,
  ConsultarCpfResultadoRoute: ConsultarCpfResultadoRoute,
  ConsultarCpfIndexRoute: ConsultarCpfIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
